# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: motion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'motion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmotion.proto\x12\x06motion\"\x07\n\x05\x45mpty\"L\n\x0cPingResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x16\n\x0e\x63uda_available\x18\x02 \x01(\x08\x12\x13\n\x0b\x64\x65vice_name\x18\x03 \x01(\t\"\xa0\x01\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0b\n\x03\x66ps\x18\x02 \x01(\x05\x12\x18\n\x10\x64uration_seconds\x18\x03 \x01(\x02\x12\x0c\n\x04seed\x18\x04 \x01(\x05\x12$\n\x06\x66ormat\x18\x05 \x01(\x0e\x32\x14.motion.MotionFormat\x12\"\n\x05model\x18\x06 \x01(\x0e\x32\x13.motion.MotionModel\"c\n\rGenerateReply\x12$\n\x06\x66ormat\x18\x01 \x01(\x0e\x32\x14.motion.MotionFormat\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0c\n\x04meta\x18\x03 \x01(\t\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t\"a\n\x0bMotionReply\x12$\n\x06\x66ormat\x18\x01 \x01(\x0e\x32\x14.motion.MotionFormat\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0c\n\x04meta\x18\x03 \x01(\t\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t*!\n\x0cMotionFormat\x12\x07\n\x03\x42VH\x10\x00\x12\x08\n\x04JSON\x10\x01*&\n\x0bMotionModel\x12\x0b\n\x07T2M_GPT\x10\x00\x12\n\n\x06MOMASK\x10\x01\x32\xab\x01\n\rMotionService\x12+\n\x04Ping\x12\r.motion.Empty\x1a\x14.motion.PingResponse\x12\x31\n\x0bGetDummyBVH\x12\r.motion.Empty\x1a\x13.motion.MotionReply\x12:\n\x08Generate\x12\x17.motion.GenerateRequest\x1a\x15.motion.GenerateReplyB\t\xaa\x02\x06Motionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'motion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\006Motion'
  _globals['_MOTIONFORMAT']._serialized_start=474
  _globals['_MOTIONFORMAT']._serialized_end=507
  _globals['_MOTIONMODEL']._serialized_start=509
  _globals['_MOTIONMODEL']._serialized_end=547
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_PINGRESPONSE']._serialized_start=33
  _globals['_PINGRESPONSE']._serialized_end=109
  _globals['_GENERATEREQUEST']._serialized_start=112
  _globals['_GENERATEREQUEST']._serialized_end=272
  _globals['_GENERATEREPLY']._serialized_start=274
  _globals['_GENERATEREPLY']._serialized_end=373
  _globals['_MOTIONREPLY']._serialized_start=375
  _globals['_MOTIONREPLY']._serialized_end=472
  _globals['_MOTIONSERVICE']._serialized_start=550
  _globals['_MOTIONSERVICE']._serialized_end=721
# @@protoc_insertion_point(module_scope)
