# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import motion_pb2 as motion__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in motion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MotionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/motion.MotionService/Ping',
                request_serializer=motion__pb2.Empty.SerializeToString,
                response_deserializer=motion__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetDummyBVH = channel.unary_unary(
                '/motion.MotionService/GetDummyBVH',
                request_serializer=motion__pb2.Empty.SerializeToString,
                response_deserializer=motion__pb2.MotionReply.FromString,
                _registered_method=True)
        self.Generate = channel.unary_unary(
                '/motion.MotionService/Generate',
                request_serializer=motion__pb2.GenerateRequest.SerializeToString,
                response_deserializer=motion__pb2.GenerateReply.FromString,
                _registered_method=True)
        self.GenerateBatch = channel.unary_unary(
                '/motion.MotionService/GenerateBatch',
                request_serializer=motion__pb2.BatchGenerateRequest.SerializeToString,
                response_deserializer=motion__pb2.BatchGenerateReply.FromString,
                _registered_method=True)
        self.Edit = channel.unary_unary(
                '/motion.MotionService/Edit',
                request_serializer=motion__pb2.EditRequest.SerializeToString,
                response_deserializer=motion__pb2.EditReply.FromString,
                _registered_method=True)
        self.EditBatch = channel.unary_unary(
                '/motion.MotionService/EditBatch',
                request_serializer=motion__pb2.BatchEditRequest.SerializeToString,
                response_deserializer=motion__pb2.BatchEditReply.FromString,
                _registered_method=True)


class MotionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Sanity check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDummyBVH(self, request, context):
        """TESTING: Prove round trip
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """TODO: Later, generate and serve actual BVH
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Edit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=motion__pb2.Empty.FromString,
                    response_serializer=motion__pb2.PingResponse.SerializeToString,
            ),
            'GetDummyBVH': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDummyBVH,
                    request_deserializer=motion__pb2.Empty.FromString,
                    response_serializer=motion__pb2.MotionReply.SerializeToString,
            ),
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=motion__pb2.GenerateRequest.FromString,
                    response_serializer=motion__pb2.GenerateReply.SerializeToString,
            ),
            'GenerateBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateBatch,
                    request_deserializer=motion__pb2.BatchGenerateRequest.FromString,
                    response_serializer=motion__pb2.BatchGenerateReply.SerializeToString,
            ),
            'Edit': grpc.unary_unary_rpc_method_handler(
                    servicer.Edit,
                    request_deserializer=motion__pb2.EditRequest.FromString,
                    response_serializer=motion__pb2.EditReply.SerializeToString,
            ),
            'EditBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EditBatch,
                    request_deserializer=motion__pb2.BatchEditRequest.FromString,
                    response_serializer=motion__pb2.BatchEditReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'motion.MotionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('motion.MotionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MotionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/Ping',
            motion__pb2.Empty.SerializeToString,
            motion__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDummyBVH(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/GetDummyBVH',
            motion__pb2.Empty.SerializeToString,
            motion__pb2.MotionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/Generate',
            motion__pb2.GenerateRequest.SerializeToString,
            motion__pb2.GenerateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/GenerateBatch',
            motion__pb2.BatchGenerateRequest.SerializeToString,
            motion__pb2.BatchGenerateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Edit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/Edit',
            motion__pb2.EditRequest.SerializeToString,
            motion__pb2.EditReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motion.MotionService/EditBatch',
            motion__pb2.BatchEditRequest.SerializeToString,
            motion__pb2.BatchEditReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
